CREATE TABLE FKS_SAVEPOINTS.DOCUMENT_MIGRATE_BOUNDS
(start_id NUMBER(38,0),
end_id NUMBER(38,0),
thread_id NUMBER(38,0));

INSERT INTO FKS_SAVEPOINTS.DOCUMENT_MIGRATE_BOUNDS (start_id, end_id, thread_id)
SELECT min(id), max(id), (part - 1)
FROM (SELECT id, NTILE(5) over(ORDER BY id) part FROM FKS_SAVEPOINTS.DOCUMENT) d
GROUP BY d.part;
